// <auto-generated />
using EntityServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityServer.Migrations
{
    [DbContext(typeof(UserAuthDbContext))]
    [Migration("20210818041232_users_seed")]
    partial class users_seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityServer.UserCreds", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("UsersCreds");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Password = "ce7a35f64c1ee87d13ba91420d48639506ba8ac2432b7b14858d4651fdd69631",
                            Username = "simon"
                        },
                        new
                        {
                            Id = 2L,
                            Password = "3bac7d66695f0726cca3969547aba728c7de6e4ad774379d7332ddd4f5e38265",
                            Username = "lake"
                        },
                        new
                        {
                            Id = 3L,
                            Password = "c64ac0577a66787781e7c3391dcd48bb2d74c84bea6d239a51e9e8b4f034b6e2",
                            Username = "palmer"
                        },
                        new
                        {
                            Id = 4L,
                            Password = "6899ed087724e0d9dfcd2c8208fcec323295fba436e02022539aa7d60aa18b73",
                            Username = "george"
                        },
                        new
                        {
                            Id = 5L,
                            Password = "9a16f64870aeeb202f411964046006e294390f81eb740f54fe8f885d2a6d4086",
                            Username = "barak"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
